[package]
name = "cargo-remote"
version = "0.1.0"
authors = ["Sebastian Geisler <sgeisler@wh2.tu-dresden.de>"]

[dependencies]
structopt = "0.1.6"
structopt-derive = "0.1.6"
cargo_metadata = "0.4.0"
log = "0.4.1"
simple_logger = "0.4.0"