[package]
name = "cargo-remote"
version = "0.1.0"
authors = ["Sebastian Geisler <sgeisler@wh2.tu-dresden.de>"]
license = "MIT"
repository = "https://github.com/sgeisler/cargo-remote"

[dependencies]
structopt = "0.1.6"
structopt-derive = {git = "https://github.com/sgeisler/structopt"}
cargo_metadata = "0.4.0"
log = "0.4.1"
simple_logger = "0.4.0"
toml = "0.4.5"